// Generated by CoffeeScript 1.8.0
describe('A go game', function() {
  beforeEach(function() {
    jasmine.addMatchers({
      toBeEmpty: function() {
        return {
          compare: function(actual) {
            return {
              pass: actual.toString().indexOf('b') === -1 && actual.toString().indexOf('w') === -1
            };
          }
        };
      },
      toHaveCellValueOf: function() {
        return {
          compare: function(actual, expected) {
            return {
              pass: actual.board[expected.x][expected.y] === expected.value
            };
          }
        };
      }
    });
    return this.game = new GoGame();
  });
  it('starts empty', function() {
    return expect(this.game).toBeEmpty();
  });
  it('should start with black', function() {
    return expect(this.game.turn).toEqual(this.game.PIECE.BLACK);
  });
  describe('when a player places a piece', function() {
    beforeEach(function() {
      return this.game.play(0, 0);
    });
    it('should not have an empty cell value', function() {
      return expect(this.game).not.toHaveCellValueOf({
        x: 0,
        y: 0,
        value: this.game.PIECE.EMPTY
      });
    });
    return it('should alternate turns', function() {
      expect(this.game.turn).toEqual(this.game.PIECE.WHITE);
      this.game.play(0, 1);
      return expect(this.game.turn).toEqual(this.game.PIECE.BLACK);
    });
  });
  return describe('when a player passes', function() {
    var originalBoard;
    originalBoard = null;
    beforeEach(function() {
      originalBoard = this.game.toString();
      return this.game.pass();
    });
    it('should not change the board', function() {
      return expect(this.game.toString()).toEqual(originalBoard);
    });
    return it('should alternate turns', function() {
      expect(this.game.turn).toEqual(this.game.PIECE.WHITE);
      this.game.pass();
      return expect(this.game.turn).toEqual(this.game.PIECE.BLACK);
    });
  });
});
